"""Initial Group and MembersGroup

Revision ID: 122f20ff1321
Revises: 724fbc8e3ba6
Create Date: 2025-04-08 11:51:12.752455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122f20ff1321'
down_revision: Union[str, None] = '724fbc8e3ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
