"""Create messages

Revision ID: 5f378b494bd3
Revises: 061ea508d199
Create Date: 2025-04-09 12:31:30.082501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f378b494bd3'
down_revision: Union[str, None] = '061ea508d199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_message', sa.String(), nullable=False),
    sa.Column('data_send', sa.Date(), nullable=True),
    sa.Column('id_send_user', sa.Integer(), nullable=True),
    sa.Column('id_send_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_send_group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['id_send_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
