"""Create Friends

Revision ID: 724fbc8e3ba6
Revises: 3b93f87f3089
Create Date: 2025-03-18 13:56:49.355889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724fbc8e3ba6'
down_revision: Union[str, None] = '3b93f87f3089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_friends', sa.Integer(), nullable=False),
    sa.Column('status_user', sa.Boolean(), nullable=False),
    sa.Column('status_friends', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_friends'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
