"""Add invite groups

Revision ID: 763681003b26
Revises: c8b60b4d1b77
Create Date: 2025-05-12 13:00:13.055072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763681003b26'
down_revision: Union[str, None] = 'c8b60b4d1b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members_group', sa.Column('is_member', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members_group', 'is_member')
    # ### end Alembic commands ###
