"""Create chat and edit messages

Revision ID: c8b60b4d1b77
Revises: 5f378b494bd3
Create Date: 2025-04-09 12:44:23.141987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b60b4d1b77'
down_revision: Union[str, None] = '5f378b494bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_friends', sa.Integer(), nullable=True),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_friends'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('date_send', sa.Date(), nullable=True))
    op.add_column('messages', sa.Column('id_chat', sa.Integer(), nullable=False))
    op.alter_column('messages', 'id_send_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('messages_id_send_group_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['id_chat'], ['id'])
    op.drop_column('messages', 'data_send')
    op.drop_column('messages', 'id_send_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id_send_group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('data_send', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_id_send_group_fkey', 'messages', 'groups', ['id_send_group'], ['id'])
    op.alter_column('messages', 'id_send_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('messages', 'id_chat')
    op.drop_column('messages', 'date_send')
    op.drop_table('chats')
    # ### end Alembic commands ###
