"""Initial Group and MembersGroup

Revision ID: ce1a1f2382bf
Revises: 122f20ff1321
Create Date: 2025-04-08 11:53:25.745471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1a1f2382bf'
down_revision: Union[str, None] = '122f20ff1321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id_created', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_created'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members_group')
    op.drop_table('groups')
    # ### end Alembic commands ###
