services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    .env_file:
      - .env-non-dev
  
  lk:
    image: lk_app
    build: 
      context: .
    ports:
      - 8000:8000
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    depends_on:
      - db